version: "3"

networks:
  mystops:
    external: true

volumes:
  mystops-postgres-data:
    external: true

services:
  postgres:
    image: postgis/postgis:13-3.3
    environment:
      - POSTGRES_USER=mystops
      - POSTGRES_PASSWORD=mystops
    networks:
      - mystops
    ports:
      - "5432:5432"
    volumes:
      - mystops-postgres-data:/var/lib/postgresql/data
