[build-system]
requires = ["uv_build>=0.11,<0.12"]
build-backend = "uv_build"

[project]
name = "mystops"
version = "3.0.0.dev0"
description = "MyStops - TriMet arrivals on a map"
authors = [{ name = "Wyatt Baldwin", email = "code@wyattbaldwin.com" }]
license = { text = "private" }
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "org-djangokit-core>=0.0.5.dev0",
    "org-djangokit-cli>=0.0.8.dev0",
    "Django>=6.1",
    "markdown>=3.10.3",
    "mercantile>=1.2.1",
    "psycopg>=3.3.4",
    "pydantic>=2.13.4",
    "pymemcache>=4.0.0",
    "requests>=2.34.2",
    "runcommands>=1.0a74.dev0",
    "tzlocal>=5.4.4",
]

[dependency-groups]
dev = [
    "ansible>=14.3.1",
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "ruff>=0.16.4",
]

[tool.uv.sources]
org-djangokit-core = { path = "../djangokit/core", editable = true }
org-djangokit-cli = { path = "../djangokit/cli", editable = true }
runcommands = { path = "../runcommands", editable = true }

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E731"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"commands.py" = ["F722", "F821"]

[tool.runcommands.globals]
env = "development"

[tool.runcommands.envs]
development = { }
production.host = "app-2.wyattbaldwin.com"
production.public_hostname = "mystops.io"
