[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mystops"
version = "3.0.0.dev0"
description = "MyStops - TriMet arrivals on a map"
authors = [ { name = "Wyatt Baldwin", email = "code@wyattbaldwin.com" } ]
license = { text = "private" }
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "org-djangokit-core>=0.0.5.dev0",
    "org-djangokit-cli>=0.0.8.dev0",
    "Django>=5.2",
    "markdown>=3.7",
    "mercantile>=1.2.1",
    "psycopg>=3.2.4",
    "pydantic>=2.10.5",
    "pymemcache>=4.0.0",
    "requests>=2.32.3",
    "runcommands>=1.0a72",
    "tzlocal>=5.2",
]

[dependency-groups]
dev = [
    "ansible>=11.1.0",
    "mypy>=1.14.1",
    "pytest>=8.3.4",
    "ruff>=0.9.2",
]

[tool.uv.sources]
org-djangokit-core = { path = "../djangokit/core", editable = true }
org-djangokit-cli = { path = "../djangokit/cli", editable = true }

[tool.setuptools.package-data]
"mystops" = [
    "**/*.css",
    "**/*.html",
    "**/*.ico",
    "**/*.js",
    "**/*.jsx",
    "**/*.toml",
    "**/*.ts",
    "**/*.tsx",
]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E731"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"commands.py" = ["F722", "F821"]

[tool.runcommands.globals]
env = "development"

[tool.runcommands.envs]
development = {}
production.host = "app-1.wyattbaldwin.com"
production.public_hostname = "mystops.wyattbaldwin.com"
