[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "mystops"
version = "0.0.0"
authors = ["Wyatt Baldwin <self@wyattbaldwin.com>"]
description = "TriMet arrivals on a map"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
ansible = "^2.9.7"
runcommands = "^1.0a56"
