# Public Settings
#
# IMPORTANT: DON'T INCLUDE SENSITIVE SETTINGS IN THIS FILE!
#
# These are settings that are shared across all environments and are
# safe to include in version control.
#
# Environment-specific settings should be added to a non-versioned
# .env.<env> file (e.g. .env.production).

[django]
APPEND_INSTALLED_APPS = ["django.contrib.gis"]
DATABASES.default.ENGINE = "django.contrib.gis.db.backends.postgis"
STORAGES.default.BACKEND = "django.core.files.storage.FileSystemStorage"
STORAGES.staticfiles.BACKEND = "djangokit.core.static.ManifestStaticFilesStorage"

[djangokit]
package = "mystops"
title = "MyStops"
description = "MyStops - TriMet arrivals on a map"
global_stylesheets = [
    "lib/bootstrap-reboot.css",
    "lib/bootstrap-icons/bootstrap-icons.css",
    "global.css",
]
webmaster = "contact@mystops.io"

[djangokit.intercept_extensions]
".json" = "application/json"
".geojson" = "application/geo+json"
