# Generated by Django 3.2.4 on 2021-06-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("route_id", models.PositiveIntegerField()),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=255,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("bus", "Bus"),
                            ("shuttle", "Shuttle"),
                            ("light-rail", "Light Rail"),
                            ("streetcar", "Portland Streetcar"),
                            ("aerial-tram", "Aerial Tram"),
                            ("commuter-rail", "Commuter Rail"),
                        ],
                        max_length=255,
                    ),
                ),
                ("name", models.TextField()),
                ("short_name", models.TextField()),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "route",
                "unique_together": {("route_id", "direction")},
            },
        ),
    ]
