---
- name: Provision
  hosts:
    - web
  become: true
  roles:
    - base
    - provision
  tags:
    - provision

- name: Prepare
  hosts:
    - localhost
  roles:
    - base
    - prepare
  tags:
    - prepare
  environment:
    DYLD_LIBRARY_PATH: /opt/homebrew/lib:/opt/homebrew/lib/postgresql@17

- name: Deploy
  hosts:
    - web
  roles:
    - base
    - deploy
  tags: deploy
