---
- name: Provision
  hosts:
    - web
  become: yes
  roles:
    - base
    - provision
  tags:
    - provision

- name: Prepare
  hosts:
    - localhost
  roles:
    - base
    - prepare
  tags:
    - prepare

- name: Deploy
  hosts:
    - web
  become: yes
  become_user: mystops
  roles:
    - base
    - deploy
  tags: deploy
