# Generated by Django 3.2.4 on 2021-06-19 23:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stop",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("stop_id", models.PositiveIntegerField(unique=True)),
                ("name", models.TextField()),
                (
                    "direction",
                    models.CharField(
                        max_length=255,
                        blank=True,
                        null=True,
                        choices=[
                            ("eastbound", "Eastbound"),
                            ("northbound", "Northbound"),
                            ("southbound", "Southbound"),
                            ("westbound", "Westbound"),
                        ],
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "stop",
            },
        ),
        migrations.CreateModel(
            name="StopRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="routes.route"
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stops.stop"
                    ),
                ),
            ],
            options={
                "db_table": "stop_route",
            },
        ),
        migrations.AddField(
            model_name="stop",
            name="routes",
            field=models.ManyToManyField(through="stops.StopRoute", to="routes.Route"),
        ),
    ]
